sudo: required
services:
    -docker

 before_install:
    - docker build -t kharding15/react-test -f ./client/Dockerfile.dev ./client


script:
    - docker run kharding15/react-test npm test -- --coverage

after_success:
    - docker build -t kharding15/multi-client ./client
    - docker build -t kharding15/multi-nginx ./nginx
    - docker build -t kharding15/multi-server ./server
    - docker build -t kharding15/multi-worker ./worker


